# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GisFIRESpreadSimulator
                                 A QGIS plugin
 GisFire modude to simulate wildfire spread. It is mainly a FARSITE implementation.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-05-21
        copyright            : (C) 2020 by Jaume Figueras
        email                : jaume.figueras@upc.edu
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GisFIRESpreadSimulator class from file GisFIRESpreadSimulator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .gis_fire_spread_simulator import GisFIRESpreadSimulator
    return GisFIRESpreadSimulator(iface)
