# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GisFIRESpreadSimulator
                                 A QGIS plugin
 GisFire modude to simulate wildfire spread. It is mainly a FARSITE implementation.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-05-21
        git sha              : $Format:%H$
        copyright            : (C) 2020 by Jaume Figueras
        email                : jaume.figueras@upc.edu
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
from PyQt5.QtWidgets import QMenu
from qgis.utils import active_plugins

# Initialize Qt resources from file resources.py
from .resources import *

# Import the code for the DockWidget
from .gis_fire_spread_simulator_dockwidget import GisFIRESpreadSimulatorDockWidget
import os.path

from .project import project as Project
from qgis.core import QgsProject

class GisFIRESpreadSimulator:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface

        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)

        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'GisFIRESpreadSimulator_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Initialization of UI references
        self._toolbarActions = dict()
        self._menuActions = dict()
        self._menu = None
        self._menu_gisfire = None
        self._toolbar = None
        self._dockwidget = None
        # Initialization of GisFIRE data layers
        self._layers = {}

        # Connect to project signals to allow plugin interacton when a new
        # project is created or loaded
        self.iface.newProjectCreated.connect(self.onNewProject)
        project = QgsProject.instance()
        if (project is not None):
            project.readProject.connect(self.onReadProject)
            project.projectSaved.connect(self.onSavedProject)
            project.homePathChanged.connect(self.onHomePathChangedProject)
            project.fileNameChanged.connect(self.onFileNameChangedProject)


    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('GisFIRESpreadSimulator', message)

    def _addToolbarActions(self):
        """Create the toolbar buttons that GisFIRE uses as shortcuts."""
        # Convert to GisFIRE Project
        action = QAction(QIcon(':/plugins/gis_fire_spread_simulator/convert.png'), self.tr('Convert GisFIRE Project'), None)
        action.triggered.connect(self.onConvertProject)
        action.setEnabled(True)
        action.setCheckable(False)
        action.setStatusTip(self.tr('Convert GisFIRE Project'))
        action.setWhatsThis(self.tr('Convert GisFIRE Project'))
        self._toolbar.addAction(action)
        self._toolbarActions['convert'] = action
        # Setup parameters
        action = QAction(QIcon(':/plugins/gis_fire_spread_simulator/setup.png'), self.tr('Setup'), None)
        action.triggered.connect(self.onSetup)
        action.setEnabled(True)
        action.setCheckable(False)
        action.setStatusTip(self.tr('Setup'))
        action.setWhatsThis(self.tr('Setup'))
        self._toolbar.addAction(action)
        self._toolbarActions['setup'] = action
        # Separator
        self._toolbar.addSeparator()
        # Set ignition point
        action = QAction(QIcon(':/plugins/gis_fire_spread_simulator/ignition.png'), self.tr('Set Ignition Point'), None)
        action.triggered.connect(self.onSetIgnitionPoint)
        action.setEnabled(True)
        action.setCheckable(False)
        action.setStatusTip(self.tr('Set Ignition Point'))
        action.setWhatsThis(self.tr('Set Ignition Point'))
        self._toolbar.addAction(action)
        self._toolbarActions['ignition'] = action
        # Separator
        self._toolbar.addSeparator()
        # Simulation Step
        action = QAction(QIcon(':/plugins/gis_fire_spread_simulator/step.png'), self.tr('Step'), None)
        action.triggered.connect(self.onSimulationStep)
        action.setEnabled(True)
        action.setCheckable(False)
        action.setStatusTip(self.tr('Step'))
        action.setWhatsThis(self.tr('Step'))
        self._toolbar.addAction(action)
        self._toolbarActions['step'] = action
        # Simulation Stop
        action = QAction(QIcon(':/plugins/gis_fire_spread_simulator/stop.png'), self.tr('Stop'), None)
        action.triggered.connect(self.onSimulationStop)
        action.setEnabled(True)
        action.setCheckable(False)
        action.setStatusTip(self.tr('Stop'))
        action.setWhatsThis(self.tr('Stop'))
        self._toolbar.addAction(action)
        self._toolbarActions['stop'] = action

    def _addMenuActions(self):
        """Create the menu entries that allow GisFIRE procedures."""
        # Convert to GisFIRE Project
        action = self._menu.addAction(self.tr('Convert GisFIRE Projet'))
        action.setIcon(QIcon(':/plugins/gis_fire_spread_simulator/convert.png'))
        action.setIconVisibleInMenu(True)
        action.triggered.connect(self.onConvertProject)
        self._menuActions['convert'] = action
        # Setup parameters
        action = self._menu.addAction(self.tr('Setup'))
        action.setIcon(QIcon(':/plugins/gis_fire_spread_simulator/setup.png'))
        action.setIconVisibleInMenu(True)
        action.triggered.connect(self.onSetup)
        self._menuActions['setup'] = action
        # Set ignition point
        action = self._menu.addAction(self.tr('Set Ignition Point'))
        action.setIcon(QIcon(':/plugins/gis_fire_spread_simulator/ignition.png'))
        action.setIconVisibleInMenu(True)
        action.triggered.connect(self.onSetIgnitionPoint)
        self._menuActions['ignition'] = action
        # Simulation Step
        action = self._menu.addAction(self.tr('Step'))
        action.setIcon(QIcon(':/plugins/gis_fire_spread_simulator/step.png'))
        action.setIconVisibleInMenu(True)
        action.triggered.connect(self.onSimulationStep)
        self._menuActions['step'] = action
        # Simulation Stop
        action = self._menu.addAction(self.tr('Stop'))
        action.setIcon(QIcon(':/plugins/gis_fire_spread_simulator/stop.png'))
        action.setIconVisibleInMenu(True)
        action.triggered.connect(self.onSimulationStop)
        self._menuActions['stop'] = action

    def _disableUi(self):
        for key in self._menuActions.keys():
            self._menuActions[key].setEnabled(False)
            self._toolbarActions[key].setEnabled(False)

    def _enableUi(self):
        for key in self._menuActions.keys():
            self._menuActions[key].setEnabled(True)
            self._toolbarActions[key].setEnabled(True)

    def _disableConvertProject(self):
        self._menuActions['convert'].setEnabled(True)
        self._toolbarActions['convert'].setEnabled(True)

    def _enableConvertProject(self):
        self._menuActions['convert'].setEnabled(True)
        self._toolbarActions['convert'].setEnabled(True)

    def _addRelations(self):
        """Create mutually exclusive relations between toolbar buttons."""
        pass

    def initGui(self):
        """Initializes the QGIS GUI for the GisFIRE Lightning plugin."""
        # Setup the menu
        menu_name = self.tr(u'Gis&FIRE')
        parent_menu = self.iface.mainWindow().menuBar()
        # Search if the menu exists (there are other GisFIRE modules installed)
        for action in parent_menu.actions():
            if action.text() == menu_name:
                self._menu_gisfire = action.menu()
        # Create the menu if does not exists and add it to the current menubar
        if self._menu_gisfire is None:
            self._menu_gisfire = QMenu(menu_name, self.iface.mainWindow().menuBar())
            actions = self.iface.mainWindow().menuBar().actions()
            self.iface.mainWindow().menuBar().insertMenu(actions[-1], self._menu_gisfire)
        # Create Lightnings menu
        self._menu = QMenu(self.tr(u'Wildfire Spread Simulator'), self._menu_gisfire)
        self._menu_gisfire.addMenu(self._menu)
        # Setup the toolbar for lightnings plugin
        self._toolbar = self.iface.addToolBar(u'GisFIRE Wildfire Spread Simulator')
        self._toolbar.setObjectName(u'GisFIRE Wildfire Spread Simulator')
        #setup the GisFire pane
        self._dockwidget = None

        # Add toolbar buttons
        self._addToolbarActions()
        # Add menu entries
        self._addMenuActions()
        # Create relations with existing menus and buttons
        self._addRelations()

        if not type(Project.getProjectName()) is str:
            self._disableUi()
        else:
            if Project.getProjectName() == '':
                self._disableUi()
            else:
                if Project.isAGisFireProject():
                    self._enableUi()
                    #TODO: Load project layers (prepareProject)
                else:
                    self._disableUi()
                    self._enableConvertProject()

    #--------------------------------------------------------------------------

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        # Remove toolbar items
        for action in self._toolbarActions.values():
            action.triggered.disconnect()
            self.iface.removeToolBarIcon(action)
            action.deleteLater()
        # Remove toolbar
        if not(self._toolbar is None):
            self._toolbar.deleteLater()
        # Remove menu items
        for action in self._menuActions.values():
            action.triggered.disconnect()
            self._menu.removeAction(action)
            action.deleteLater()
        # Remove menu
        if not(self._menu is None):
            self._menu.deleteLater()
        # Remove dockwidget
        if self._dockwidget != None:
            self._dockwidget.hide()
            self._dockwidget.deleteLater()
        # Remove the menu_gisfire only if I'm the only GisFIRE module installed
        count = 0
        for name in active_plugins:
            if name.startswith('GisFIRE-'):
                count += 1
        if count == 1:
            if not(self._menu_gisfire is None):
                self.iface.mainWindow().menuBar().removeAction(self._menu_gisfire.menuAction())
                self._menu_gisfire.menuAction().deleteLater()
                self._menu_gisfire.deleteLater()
        # Disconnect Project slots
        self.iface.newProjectCreated.disconnect(self.onNewProject)
        project = QgsProject.instance()
        if (project is not None):
            project.readProject.disconnect(self.onReadProject)
            project.projectSaved.disconnect(self.onSavedProject)
            project.homePathChanged.disconnect(self.onHomePathChangedProject)
            project.fileNameChanged.disconnect(self.onFileNameChangedProject)

    #--------------------------------------------------------------------------

    def onReadProject(self):
        """Slot connection for the Read Project signal. It checks if the loadaed
        project is a GisFIRE project and updates the GisFIRE UI agordingly"""
        if Project.isAGisFireProject():
            #TODO: Load project layers (prepareProject)
            self._enableUi()
        else:
            self._enableConvertProject()

    def onNewProject(self):
        """Slot connection for the New Project signal. It disables all the
        GisFIRE UI because the project has to be saved to be converted to a
        GisFIRE project"""
        self._disableUi()

    def onSavedProject(self):
        """Slot connection for the Save Project signal. It enables convert
        project UI because once the project is saved it can be converted to a
        GisFIRE project"""
        if not Project.isAGisFireProject():
            self._enableConvertProject()

    def onHomePathChangedProject(self):
        if Project.isAGisFireProject():
            # TODO: Copy geopackage
            pass

    def onFileNameChangedProject(self):
        if Project.isAGisFireProject():
            # TODO: Copy geopackage
            pass

    #--------------------------------------------------------------------------

    def onConvertProject(self):
        pass

    def onSetup(self):
        pass

    def onSetIgnitionPoint(self):
        pass

    def onSimulationStep(self):
        pass

    def onSimulationStop(self):
        pass
